/**
 * HTML preview sandbox proxy.
 *
 * The `/vfs` tab embeds us inside an outer `<iframe sandbox="allow-scripts
 * allow-same-origin allow-forms">` pointed at this page, then ships us the
 * user's HTML via postMessage. We host that document inside an inner iframe
 * with the same sandbox tokens, so:
 *
 *   - Inline `<script>`, DOMContentLoaded handlers, `onclick=` all RUN. We
 *     inherit the manifest `sandbox` CSP (`script-src 'self' 'unsafe-inline'
 *     'unsafe-eval' https: data: blob:`), unlike `extension_pages` which is
 *     locked to `script-src 'self'` (MV3 forbids `'unsafe-inline'` for
 *     extension pages — inline scripts in srcdoc there are silently blocked).
 *   - `allow-same-origin` is harmless because our origin is opaque (the
 *     sandbox page's own URL), not the parent sidepanel's extension origin.
 *     An escaping script can't reach sidepanel DOM, storage, or IPC — the
 *     Chrome warning about `allow-scripts + allow-same-origin` escaping the
 *     sandbox only matters when "same origin" means "the parent page's
 *     privileged origin", which it doesn't here.
 *   - `allow-forms` is granted so `<form>` submissions work; the outer
 *     iframe's own sandbox excludes `allow-top-navigation` and `allow-popups`,
 *     so `target=_top` or `window.open()` is a no-op.
 *
 * Wire protocol (handshake-based — see below):
 *
 *   sandbox → host:  { type: 'sandbox:ready' }                          (once on load)
 *   host   → sandbox: { type: 'html-preview:set', html, name }          (after ready)
 *   host   → sandbox: { type: 'html-preview:clear' }
 *
 * Handshake rationale: the host can mount the outer iframe and call
 * `iframe.contentWindow.postMessage(...)` before our top-level script has
 * registered its `message` listener. Chromium does NOT reliably queue
 * messages sent to a window before listeners attach — under load the
 * first `set` is silently dropped, leaving the inner iframe blank. The
 * `sandbox:ready` event lets the host flush its pending payload only
 * after we are listening.
 *
 * Trust model: the HTML we render is the user's own VFS content, either
 * hand-written or generated by an agent they control. Same trust level as
 * the prior "download file, open in new Chrome tab" workflow — the opaque
 * origin contains the blast radius.
 */

// ─── Types ───────────────────────────────────────────────────────────

interface SetMessage {
  type: 'html-preview:set';
  html: string;
  name: string;
}
interface ClearMessage {
  type: 'html-preview:clear';
}
type InboundMessage = SetMessage | ClearMessage;

interface ReadyMessage {
  type: 'sandbox:ready';
}

// Sandbox tokens for the inner iframe — fixed per the spec; we never
// accept an override from the host. `allow-popups` and
// `allow-top-navigation` are deliberately excluded so a hostile previewed
// document can't navigate or spawn windows via `target=_top` / `window.open`.
// `allow-modals` is granted so `alert()` / `confirm()` / `prompt()` (and
// `window.print()`) work — without it Chrome drops the calls silently with
// "document is sandboxed, and the 'allow-modals' keyword is not set".
// Modals are scoped to the inner iframe and can't escape to the parent, so
// granting this is safe.
const INNER_SANDBOX = 'allow-scripts allow-same-origin allow-forms allow-modals';

// ─── State ───────────────────────────────────────────────────────────

/** The single inner iframe, replaced on each `set`. */
let innerIframe: HTMLIFrameElement | null = null;

// ─── Handshake ───────────────────────────────────────────────────────

function announceReady(): void {
  // Diagnostic: log so the host side (and DevTools) can confirm the
  // sandbox script actually ran.
  // eslint-disable-next-line no-console
  console.log('[html-preview.sandbox] ready, announcing to host');
  const message: ReadyMessage = { type: 'sandbox:ready' };
  window.parent.postMessage(message, '*');
}

// Defer until DOM is parsed so the message goes out at the same instant
// the page is ready to receive replies. Top-level code would also work
// for a module script (modules are deferred by default), but DOMContentLoaded
// is the clearest contract: "the document is parsed, any scripts inside it
// have started executing, we are ready to receive".
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', announceReady, { once: true });
} else {
  // Already past DOMContentLoaded (script was injected late) — announce now.
  announceReady();
}

// ─── Inbound message routing ──────────────────────────────────────────

window.addEventListener('message', (event: MessageEvent) => {
  const data = event.data as InboundMessage | null | undefined;
  if (!data || typeof data !== 'object') return;
  // Authenticate the source. Both sides have opaque origins so
  // `event.origin === 'null'` everywhere — useless for ACL. The window
  // reference check is the real boundary: only the host that owns this
  // iframe (window.parent) is allowed to drive us. Any foreign window
  // (devtools probes, malicious sibling iframes elsewhere) is dropped.
  if (event.source !== window.parent) return;

  switch (data.type) {
    case 'html-preview:set':
      // eslint-disable-next-line no-console
      console.log('[html-preview.sandbox] received set', {
        name: data.name,
        bytes: data.html.length,
      });
      renderHtml(data.html, data.name);
      break;
    case 'html-preview:clear':
      // eslint-disable-next-line no-console
      console.log('[html-preview.sandbox] received clear');
      clearInner();
      break;
  }
});

// ─── Inner iframe construction ───────────────────────────────────────

function renderHtml(html: string, name: string): void {
  // Hot-replace: tear down the previous iframe before mounting a new one
  // so we never have two live documents at once. The previous one would
  // keep running scripts in the background if we didn't, wasting CPU and
  // potentially leaking listeners / timers.
  if (innerIframe) {
    innerIframe.remove();
    innerIframe = null;
  }

  const iframe = document.createElement('iframe');
  iframe.setAttribute('sandbox', INNER_SANDBOX);
  iframe.setAttribute('title', name);

  // srcdoc is the cheap way to ship the document — no fetch roundtrip,
  // no extra origin. The inner iframe inherits our manifest `sandbox`
  // CSP (permissive), so inline scripts in the document run.
  iframe.srcdoc = html;

  document.body.appendChild(iframe);
  innerIframe = iframe;
}

function clearInner(): void {
  if (innerIframe) {
    innerIframe.remove();
    innerIframe = null;
  }
}
